chore: add security target

diff --git a/app/templates/_Makefile b/app/templates/_Makefile
--- a/app/templates/_Makefile
+++ b/app/templates/_Makefile
@@ -91,12 +91,13 @@ githooks: $(GITHOOKS) ## Symlink githooks
 
 .PHONY: release-dry
 release-dry: $(NODE_MODULES) ## Dry run of `release` target
-	$(UNLEASH) -d --type=$(shell $(CONVENTIONAL_RECOMMENDED_BUMP) -p angular)
+	@$(UNLEASH) -d --type=$(shell $(CONVENTIONAL_RECOMMENDED_BUMP) -p angular)
 
 
 .PHONY: release
-release: $(NODE_MODULES) ## Versions, tags, and updates changelog based on commit messages
-	$(UNLEASH) --type=$(shell $(CONVENTIONAL_RECOMMENDED_BUMP) -p angular)
+release: $(NODE_MODULES) security ## Versions, tags, and updates changelog based on commit messages
+	@$(UNLEASH) --type=$(shell $(CONVENTIONAL_RECOMMENDED_BUMP) -p angular) --no-publish
+	@$(NPM) publish
 
 
 .PHONY: lint
@@ -112,12 +113,20 @@ lint-fix: $(NODE_MODULES) $(PRETTIER) $(ALL_FILES) ## Reprint code (prettier, es
 
 .PHONY: security
 security: $(NODE_MODULES) ## Check for dependency vulnerabilities.
-	@$(NPM) install --package-lock-only
-	@$(NPM) audit
+	@# remove lockfile, reinstall to get latest deps and regen lockfile
+	@rm $(YARN_LOCK) || true
+	@$(YARN)
+	@$(YARN) audit || EXIT_CODE=$$?; \
+	if [ $$EXIT_CODE -gt 15 ] ; then \
+		echo "'yarn audit' exited with error code $$EXIT_CODE, critical vulnerabilities found!"; \
+		exit 1; \
+	else \
+		echo "'yarn audit' exited with error code $$EXIT_CODE, no critical vulnerabilities found."; \
+	fi
 
 
 .PHONY: prepush
-prepush: $(NODE_MODULES) lint coverage security ## Git pre-push hook task. Run before committing and pushing.
+prepush: $(NODE_MODULES) lint coverage ## Git pre-push hook task. Run before committing and pushing.
 
 
 .PHONY: test
